### ISSUE TITLE
Broken dependencies caused by missing baseUrl in _config.yml

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo-playground#2]
https://github.com/accordproject/ergo-playground/blob/4e7a37e9a794a4136eb7948c95f06ee7f7a42793/_config.yml#L7

line needs to be replaced with 
```
baseurl: "https://accordproject.github.io/ergo-playground/"
```

**Comment by jeromesimeon** [comment]
Good catch. I need to find a better way to handle the base url during testing, but for now this is fixed.
