### ISSUE TITLE
Built-in Ergo Samples

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/ergo-playground#6]
In the playground, a list of samples contracts would help to accelerate understanding.

The samples could be taken from the https://github.com/accordproject/cicero-template-library, or https://github.com/accordproject/ergo/tree/master/examples

For example, see the Monaco playground https://microsoft.github.io/monaco-editor/monarch.html

**Comment by jeromesimeon** [comment]
The playground now has built-in sample obtained from:
https://github.com/accordproject/cicero-template-library/tree/ergo-templates
